updata metax megatron install

diff --git a/.github/workflows/functional_tests_train.yml b/.github/workflows/functional_tests_train.yml
--- a/.github/workflows/functional_tests_train.yml
+++ b/.github/workflows/functional_tests_train.yml
@@ -220,15 +220,19 @@ jobs:
           echo "Python location: $(which python)"
           echo "Python version: $(python --version)"
 
-          # Install Megatron-LM-FL
-          pip install megatron_core==0.1.0+megatron0.15.0rc7 \
-            --extra-index-url https://resource.flagos.net/repository/flagos-pypi-hosted/simple \
-            || { echo "❌ Megatron-LM-FL install failed"; exit 1; }
-          echo "✅ Megatron-LM-FL installed successfully"
+          git clone \
+            "https://github.com/flagos-ai/Megatron-LM-FL.git" /tmp/Megatron-LM-FL
+          git -C /tmp/Megatron-LM-FL checkout d092f8df49f7c0b5b4cae42d036b7e4a26b8fc81
+
+          echo "Installing Megatron-LM-FL via pip..."
+          pip install /tmp/Megatron-LM-FL --no-build-isolation --root-user-action=ignore \
+            || { echo "Megatron-LM-FL install failed"; exit 1; }
 
           # Install TransformerEngine-FL and dependencies
           git clone --depth 1 https://github.com/flagos-ai/TransformerEngine-FL.git /workspace/TransformerEngine-FL \
             || { echo "❌ TransformerEngine-FL clone failed"; exit 1; }
+          git -C /workspace/TransformerEngine-FL checkout d092f8df49f7c0b5b4cae42d036b7e4a26b8fc81 \
+            || { echo "❌ TransformerEngine-FL checkout failed"; exit 1; }
           TE_FL_SKIP_CUDA=1 pip install /workspace/TransformerEngine-FL --no-build-isolation \
             || { echo "❌ TransformerEngine-FL install failed"; exit 1; }
           echo "✅ TransformerEngine-FL installed successfully"
